model:
  base_learning_rate: 1.0e-05
  target: zero123plus.model.MVDiffusion
  params:
    drop_cond_prob: 0.1

    stable_diffusion_config:
      pretrained_model_name_or_path: TencentARC/InstantMesh
      custom_pipeline: ./zero123plus

data:
  target: src.data.objaverse_zero123plus.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    train:
      target: src.data.objaverse_zero123plus.ObjaverseData
      params:
        root_dir: /content/drive/MyDrive/3ddata_train2
        meta_fname: lvis-annotations-train.json
        image_dir: merged_multiview_train
        validation: false
    validation:
      target: src.data.objaverse_zero123plus.ObjaverseData
      params:
        root_dir: /content/drive/MyDrive/3ddata_train2
        meta_fname: lvis-annotations-train.json
        image_dir: merged_multiview_train
        validation: true


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 2000
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: 100
    gradient_clip_val: 1.0
    val_check_interval: 7000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
